### ISSUE TITLE
요구사항

### ISSUE THREAD

**Issue by donggi-lee-bit** [f-lab-edu/sendzy#1]
### 필수 기능

**회원 가입**
- 사용자는 회원 가입을 할 수 있어야 합니다.

**로그인**
- 사용자는 로그인할 수 있어야 합니다.

**거래 내역 및 잔액 조회**
- 로그인한 사용자는 거래 내역 및 잔액을 조회할 수 있어야 합니다.

**송금**
- 로그인한 사용자는 다른 사용자에게 돈을 보낼 수 있어야 합니다.
- 돈을 보낸지 3일이 지나도 수취하지 않으면 송금이 자동으로 취소됩니다.

**송금 취소**
- 송금한 돈을 사용자가 수취하지 않았다면 취소가 가능해야 합니다.

**수취**
- 다른 사용자가 보낸 돈을 수취할 수 있어야 합니다.

### 추가 기능

**예약 송금**
- 사용자는 송금을 특정 시간에 보낼 수 있어야 합니다.

**정산하기(더치페이)**
- 사용자는 정산하기(더치페이) 다른 사용자에게 요청을 보낼 수 있어야 합니다.

**Comment by f-lab-maverick** [comment]
조금만 더 구체적인 기획을 해주시면 좋겠습니다.

예를 들어, 회원가입과 로그인의 기능 명세를 다음과 같이 적어주셨습니다.

```
회원 가입
사용자는 회원 가입을 할 수 있어야 합니다.

로그인
사용자는 로그인할 수 있어야 합니다.
```

아래 정도의 구체성을 띄게 해주세요.

```
회원가입
- OAuth등을 사용하지 않음
- 회원 데이터와 비밀번호 데이터의 직접 관리, 암호화에 대한 이해를 위해 id, password를 입력받는 현태로 회원가입 구현
- id는 이메일 형태로 입력받고 중복체크를 진행
- 패스워드는 SHA-256 암호화 검토

로그인
- id, password를 입력받아 로그인을 할 수 있음
- 세션방식과 토큰방식의 로그인 방식을 고려중. 인증 방식을 학습하며 확정 예정
- 패스워드가 네트워크를 통해 입력될 떄 통신안전을 위해 SSL 레이어 도입 예정(HTTPS)
```


또한 기능도 조금 더 구체적으로 적어주세요.
-로그인한 사용자는 거래 내역 및 잔액을 조회할 수 있어야 합니다.

=> 인증된 사용자는 거래내역을 조회할 수 있다. 이 때 거래내역은 사용자가 송금했거나, 송금받은 내역만 보여진다.
=> 인증된 사용자는 본인 계좌(지갑)의 잔액을 조회할 수 있다. 잔액은 송금, 수취내역과 불일치가 발생하면 안되기 때문에 데이터 일관성에 유의해야 한다.
=> (아이디어) 잔액 데이터를 아예 관리하지 않고, 송금/수취데이터를 실시간으로 계산해서 보여주는건 어떨까?
=> (고민할 부분) 잔액데이터를 별도 컬럼으로 관리하면 동시성 이슈를 어떻게 피할 수 있을까?

**Comment by donggi-lee-bit** [comment]
피드백 해주신 내용을 바탕으로 더 상세하게 작성해보았습니다. 기획을 작성하면서 정산하기(더치페이) 기능은 이 프로젝트의 목적을 벗어나는 기능인 것 같아 제외하였습니다.

```
## 필수 기능

회원 가입
- OAuth는 현재로써 고려하지 않음
- 회원 데이터는 암호화에 대한 이해를 위해 id, password를 입력하는 형태로 구현
- id는 이메일 형태로 입력 받고, 중복 검사를 진행
- 패스워드는 SHA-256과 같은 단방향 해시를 검토

로그인
- id, password를 입력받아 로그인
- 로그인 상태 관리는 세션 방식과 토큰 방식을 고려하며, 인증 방식에 대한 학습 후 확정 예정
- 패스워드가 네트워크를 통해 전송될 때 통신 안전을 위해 SSL 레이어 도입 예정(HTTPS)

송금
- 송금할 대상의 이메일(혹은 계좌번호)을 입력하고, 송금할 금액을 입력
- 이메일 입력 시 회원 가입 여부 확인. 가입된 회원에게만 송금 가능하도록 구현
- 송금 요청 시 거래 내역에 송금 이력을 추가
- 송금 요청 시 수취인이 수락할 때까지 출금에 대한 아래 2가지 방식 고려
  1. 중간 계좌를 만들어 중간 계좌에 돈을 예치해 두는 방식
  2. 계좌의 총액은 그대로인 채 마이너스 이력을 남기는 방식

송금 취소
- 수취인은 송금을 수락할 수도, 수락하지 않을 수도 있음
- 수취인이 수락하지 않았을 경우 송금 취소 가능
- 수취인이 3일 동안 수락하지 않을 경우 자동으로 송금 취소

수취
- 수취 요청을 수락하면 거래 내역에 수취 이력을 추가
- 수취인이 송금을 거절할 수 있음. 거절된 경우 거래가 취소되고 거래 내역에 반영

거래 내역 및 잔액 조회
- 인증된 사용자는 거래 내역을 조회할 수 있음. 이 때 거래 내역은 사용자가 송금하거나 수취한 내역만 보여야함
- 인증된 사용자는 본인 계좌의 잔액을 조회할 수 있음. 잔액은 송금, 수취 내역과 불일치가 발생하지 않아야 하며, 데이터의 일관성에 유의해야 함

## 추가 기능

예약 송금
- 지정한 날짜, 시간에 지정한 금액을 송금
- 매일, 매주, 매달 등 자동 이체 형태로 기능 확장 가능
```
