### ISSUE TITLE
와이어 프레임

### ISSUE THREAD

**Issue by donggi-lee-bit** [f-lab-edu/sendzy#2]
## Description

- 와이어 프레임을 작성해 기능과 화면 흐름을 시각적으로 구체화 해주세요.

**Comment by f-lab-maverick** [comment]
@donggi-lee-bit 
고생하셨습니다.
PR에 있는 와이어프레임을 위 이슈에도 추가해주세요.

화면 하나마다 어떤 기능이 필요할지를 러프하게 정의할 것입니다. 와이어프레임과 시퀀스다이어그램을 기반으로 어떤 API가 필요할지, 어떤 기능에 대한 개발이 필요할지 신규이슈를 작성해주세요.

기능에 대한 이슈를 작성하실 때에는 아래 내용을 포함하여 작성해주세요.
- 기능에 대한 명세
- 성공조건
- 실패 또는 예외발생시 처리 흐름
- 고려해야할 부분

모든 기능을 다 만들 필요는 없습니다. 가장 먼저 회원가입과 로그인 페이지에 대한 이슈부터 시작해보시죠!

**Comment by donggi-lee-bit** [comment]
현재 #4 에 포함된 와이어프레임 이미지입니다.

<img width="756" alt="image" src="https://github.com/user-attachments/assets/47f89ae2-2115-4287-965d-18b251c3143c">
