### ISSUE TITLE
회원 가입 API

### ISSUE THREAD

**Issue by donggi-lee-bit** [f-lab-edu/sendzy#6]
### 기능 명세

- 이메일, 비밀번호를 입력받아 회원을 등록하는 회원 가입 API
- ~~중복 이메일을 검사하기 위한 API~~

### 성공 조건

- 사용자가 입력한 이메일이 아래 조건을 만족하는 경우
  - 지정한 정규식에 일치하는 영문 이메일
  - 최소 5자 이상(a@b.c)
  - 최대 100자 이하
  - 중복된 이메일이 아닐 경우
- 비밀번호가 아래 조건을 만족하는 경우
  - 최소 8자 이상
  - 최대 32자 이하
  - 3가지 문자 타입을 모두 포함(영어 소문자, 대문자, 숫자)

### 실패 또는 예외 발생 시 처리 흐름

- 잘못된 이메일 형식 입력 시 "올바른 이메일 주소를 입력해주세요." 메세지가 출력되어야 함
- 이메일이 중복될 경우 "이미 존재하는 이메일입니다." 메세지가 출력되어야 함
- 비밀번호가 누락된 경우 "비밀번호를 입력하세요." 메세지가 출력되어야 함
- 서버 오류 발생 시 "서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요." 메세지가 출력되어야 함

### 고려해야 할 부분

- 비밀번호 암호화
  - 클라이언트에서 암호화하여 전송하면 안 되는지?
  - 서버에서는 어떤 암호화를 사용해야 하는지?
  - 암호화 시 고려해야 하는 부분은 어떤 게 있을지?

**Comment by f-lab-maverick** [comment]
API 스펙 정의 필요
참고링크: https://developers.kakao.com/docs/latest/ko/kakaologin/rest-ap

**Comment by f-lab-maverick** [comment]
이메일이 올바르게 입력된 경우 ->

최소 글자수, 최대 글자수
이메일 형식이 어떻게 되는지 정규식
한글이메일 되는지?
비밀번호 최소/최대 글자수
비밀번호 형식 정규식
**암호화 알고리즘** -> 알고리즘별 해시값 길이 확인

알고리즘 자료조사
- 단방향 암호화 알고리즘
- 레인보우테이블 이슈
- salt / pepper 찾아보기.

**Comment by donggi-lee-bit** [comment]
비밀번호 암호화와 관련하여 자료 조사한 내용입니다. 😄 @f-lab-maverick 

### 비밀번호 암호화

비밀번호와 같이 민감한 데이터는 해싱을 통해 보호하는 것이 필요합니다. 암호화 알고리즘에는 단방향 암호화, 양방향 암호화가 있지만 양방향 암호화를 사용할 때 키가 유출될 경우 대규모 데이터 유출 위험이 있어 단방향 암호화를 사용합니다.

단방향 암호화는 주로 해싱 알고리즘을 이용해 데이터를 안전하게 보호합니다. 이때 특정 해시 알고리즘으로 데이터를 해싱하면 항상 같은 해시 값을 갖게 됩니다. 이런 특징을 이용해 해시 함수의 해시 값들을 정리한 테이블을 레인보우 테이블(Rainbow Table)이라고 합니다. 레인보우 테이블을 이용해 미리 계산된 해시 값으로 데이터를 추출하는 공격을 레인보우 공격(Rainbow Attack)이라고 합니다.

이러한 문제를 보완하기 위해 솔팅(salting)과 페퍼(pepper)가 사용됩니다. 솔팅은 데이터마다 다르게 무작위 값을 추가하여 같은 데이터라도 다른 해시 값을 갖게 하여 레인보우 테이블 공격을 방지하는데 유리합니다. 페퍼는 솔팅과 유사하지만 모든 데이터에 고정된 값을 추가하여 해시 값을 만듭니다. 또한 페퍼는 서버 내에서 관리되기 때문에 데이터베이스가 유출되어 공격자가 해시 값과 솔트를 입수해도 비밀번호를 추론하기 어렵게 만듭니다. 

### 단방향 알고리즘의 종류

단방향 암호화 알고리즘의 종류에는 SHA, MD5, bcrypt, scrypt, PBKDF2 등이 있습니다.

SHA (Secure Hash Algorithm)

- SHA-1는 160비트의 해시를 생성하는 해시 함수입니다. 현대 컴퓨팅이 발전하면서 해시의 충돌을 찾아낼 가능성이 높아져 SHA-1 함수는 안전하지 않다고 평가되면서 이를 개선한 SHA-2가 등장하게 됩니다.
- SHA-2는 여러 버전의 해시 함수가 있으며 대표적으로 SHA-256, SHA-512가 있습니다. 각각 256비트와 512비트의 해시를 생성합니다.

MD5 (Message Diagest Algorithm 5)

- MD5는 128비트 해시 값을 생성하는 고속 해시 함수입니다.
- MD5 또한 해시 충돌 발생 위험이 있어 비밀번호 암호화에는 권장되지 않는 방법입니다.

bcrypt

- 레인보우 테이블 공격을 방지하기 위해 각 데이터에 솔팅과 키 스트레칭을 적용한 해시 함수입니다.
- 또한 보안 강도를 조절할 수 있는 cost factor가 있어 공격자의 공격 난이도를 조절할 수 있습니다.
- 기본적으로 184비트 길이의 해시 값을 생성하며, 보통 60자의 Base64 인코딩 문자열로 표현됩니다.

scrypt

- brcypt를 개선한 버전으로 메모리 집약적 설계가 암호화에 사용되어 많은 메모리를 메모리를 필요로 합니다.
- 이를 통해 공격자가 GPU를 이용한 대규모 병렬 연산 공격을 어렵게 합니다.
- scrypt의 길이는 사용자가 설정할 수 있으며 일반적으로 256비트 또는 그 이상의 해시 길이로 설정합니다.

**Comment by donggi-lee-bit** [comment]
회원 가입 API 스펙입니다. @f-lab-maverick 

<h3>기본 정보</h3>

메서드 | URL
-- | --
POST | /v1/signup

사용자를 회원으로 등록합니다. 이메일과 비밀번호 값은 성공 조건의 형식을 충족해야 회원 가입 정상적으로 요청됩니다. 성공 조건의 형식을 충족하지 못한 경우 에러 응답을 받습니다.
<h3>요청</h3>
<p><strong>본문</strong></p>

이름 | 타입 | 설명 | 필수
-- | -- | -- | --
email | String | 사용자 이메일 | O
password | String | 사용자 비밀번호 | O

<h3>예제</h3>
<p><strong>요청</strong></p>
<pre><code class="language-json">curl -X POST &quot;&lt;https://api.sendzy.com/v1/signup&gt;&quot; \
-H &quot;Content-Type: application/json&quot; \
-d '{
  &quot;email&quot;: &quot;user@hello.com&quot;,
  &quot;password&quot;: &quot;yourPassw0rd&quot;
}'
</code></pre>
</br>
<p><strong>응답: 성공</strong></p>
<pre><code class="language-json">HTTP/1.1 200 OK
</code></pre>
</br>
<p><strong>응답: 실패, 잘못된 형식의 이메일이 입력된 경우</strong></p>
<pre><code class="language-json">HTTP/1.1 400 Bad Request
{
    &quot;message&quot;: &quot;올바른 형식의 이메일 주소를 입력해주세요.&quot;
}
</code></pre>
</br>
<p><strong>응답: 실패, 이메일이 중복될 경우</strong></p>
<pre><code class="language-json">HTTP/1.1 409 Conflict
{
    &quot;message&quot;: &quot;이미 존재하는 이메일입니다.&quot; 
}
</code></pre>
</br>
<p><strong>응답: 실패, 비밀번호가 누락된 경우</strong></p>
<pre><code class="language-json">HTTP/1.1 400 Bad Request
{
    &quot;message&quot;: &quot;비밀번호를 입력하세요.&quot;
}
</code></pre>
</br>
<p><strong>응답: 실패, 서버 오류가 발생한 경우</strong></p>
<pre><code class="language-json">HTTP/1.1 500 Server Error
{
    &quot;message&quot;: &quot;서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.&quot;
}
</code></pre>
